#!/bin/bash
set -e

# Remove links and config
if [ "$1" == "remove" ]
then
    if [ -f "/usr/bin/magiwol" ]
    then
        rm "/usr/bin/magiwol"
    fi

    if [ -f "$HOME/.magiwol" ]
    then
        rm "$HOME/.magiwol"
    fi
fi

# Purge debconf
if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
    db_purge
fi

# Done
exit 0
